### PR TITLE
Fallback to pynput from keyboard library

### PR DESCRIPTION
**Pull request by deathbeam**
This library do not requires root. This is alternative to #114.

Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

### CODE REVIEW

**Comment by deathbeam** [comment]
Looks like this has downside of not working without X

**Comment by deathbeam** [comment]
Changed this to use pynput as fallback to support all scenarios

**Comment by Ethck** [comment]
I definitely want to merge this, but in its current state I cannot due to errors with pynput and the no-keybind version.

The pynput error:
This is occurring on Windows, not sure if it affects other platforms.
After copying an item with control+c, I can not use any other keybind, nor can I select text. I think the reason for this is that some key keeps getting pressed after the first item. There is no trace for this error.

The no-keybind error:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "PythonFiles\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "poeTradeLookup\utils\input.py", line 45, in run
    self.callback(text)
  File "poeTradeLookup\utils\input.py", line 68, in <lambda>
    self.clipboard_watcher = ClipboardWatcher(lambda text: self.combination_to_function[Keyboard.CLIPBOARD_HOTKEY](text))
TypeError: <lambda>() takes 0 positional arguments but 1 was given

I'm curious, can you replicate these errors?

**Comment by Ethck** [comment]
I will test again in a couple of hours, and upon success will merge into dev.

**Pull request merged**
