### PR TITLE
Move dependencies to requirements.txt file

### PR DESCRIPTION
**Pull request by deathbeam**
This is standardized format for Python dependencies

Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

### CODE REVIEW

**Comment by Ethck** [comment]
Currently I am using Poetry to handle dependencies, it's in a bit of a broken state right now, but what advantage do you believe `requirements.txt` has over `poetry`? I'm interested.

**Comment by deathbeam** [comment]
Well requirements.txt works out of the box as its supported by pip (and its basically just list of dependencies, nothing else, so very simple), I never really used poetry before so can't tell what are advantages of that one.

**Comment by Ethck** [comment]
Fair enough. I'll probably revert to requirements.txt for now. Poetry seems to be a lot of hassle.

**Comment by deathbeam** [comment]
Looks like this was implemented in https://github.com/Ethck/Path-of-Accounting/commit/87dcd3465efc3934d9ce47ef70c989aebee046e6 so closing

**Pull request closed without merging**
