### PR TITLE
Reuse and layout the GUI window

### PR DESCRIPTION
**Pull request by deathbeam**
- Instead of setting fixed size for the window, just let it size itself
  based on its contents
- Instead of creating entirely new window each time, just hide and show
  the already created window, and just update its contents (this fixes
  some issues for example on Linux, where the testGui window was never
  being hidden for me, even after .destroy())

Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

### CODE REVIEW

**Comment by Ethck** [comment]
I will probably merge this later. If you could though, can you refactor the gui to accept a more function-based approach? For example, I plan on incorporating multiple different GUI views into Path of Accounting (i.e. simple search, advanced search. I'll admit, tkinter is not my strong suit.

**Comment by deathbeam** [comment]
Im not sure how would I do this function based to improve it tho, like I guess I could just extract the prepare_gui method and then just pass the root to show_price. Or maybe I can just extract the part that is making the core window and move labels to separate method, I guess that way the prepare_gui function would be reusable

**Comment by Ethck** [comment]
By function based I'm more concerned about basically just being able to call a function to get the window I want (i.e. bring up the simple search vs bring up the advanced search). My idea for this is that you can have a setup function, but then all of the GUI elements (labels, pictures, etc.) are in their own separate function called by whatever hotkey enables it.

**Comment by deathbeam** [comment]
Well each of those different windows should also be different tkinter Toplevel window imo, so completely separated. Even though maybe I can instead just remove all children from the base window and repopulate with new ones. I will try to do that then

**Comment by deathbeam** [comment]
Alright I figured out pretty clean way how to refactor this to be nice and reusable, I will update it later today

**Comment by deathbeam** [comment]
Alright updated. I still need to test the changes, I will test them when I arrive home (also I still need to rebase)

**Comment by deathbeam** [comment]
Updated again and tested, its working.

**Comment by Ethck** [comment]
Looks great! Merging now.

**Pull request merged**
