### PR TITLE
Scroll Stash, check if PoE on Windows

### PR DESCRIPTION
**Pull request by rhzk**
* Added hotkeys for scrolling in the stash tab
* On Windows it will check if the current active window is Path of Exile before doing hotkeys

I could however not find a way to consume the scroll wheel command with this API

### CODE REVIEW

**Comment by Ethck** [comment]
I like the ideas behind this PR. When you're ready and have it fully implemented I would love to merge this! Also, if you haven't already please join the PoA discord! (link in the README)

**Comment by rhzk** [comment]
I might be blind but i do not see a discord link in the README

Edit: Found it, was hiding in gui branch, but its invalid now :/

**Comment by rhzk** [comment]
Btw what branch should I use?
Was also thinking about adding some gui features, for example a option to select mods to include in the search. And if you could post a new discord link :)

**Comment by Ethck** [comment]
Use the dev branch to base things off of, and target that with your PRs. Here's the discord link: discord.gg/BUV2x6N

**Pull request closed without merging**
