### PR TITLE
Fallback to clipboard polling if fail to import keyboard module

### PR DESCRIPTION
**Pull request by woefulwabbit**
On Linux, root permissions is required to use the keyboard module.

This change will fallback to call the watch_clipboard_no_hotkey() if there
is a failure to import the keyboard module

### CODE REVIEW

**Comment by deathbeam** [comment]
Wouldn't this have unintended side effects with GUI enabled? Also you are disabling other hotkeys with this as well without sudo. Maybe instead switching to https://pynput.readthedocs.io/en/latest/keyboard.html what do not requires root would be better?

**Comment by woefulwabbit** [comment]
Yes, hotkeys will have to be disabled if using the keyboard module without sudo, so the intention of this patch is to allow basic Ctrl-C functionality to work.

I agree though, a keyboard library that doesn't require root would be a better solution

**Comment by deathbeam** [comment]
I implemented that in #115. Both pynput and keyboard have different issues, e.g pynput do not works without X server, keyboard do not works without sudo. So what I did in that PR is that first it tries keyboard, then pynput and when everything fails it will at least use clipboard polling.

**Comment by Ethck** [comment]
Closing this. Once errors have been fixed, I will merge #115. Thanks for starting the PR though!

**Pull request closed without merging**
